# Generated by Django 6.1.1 on 2026-09-18 09:44

import django.db.models.deletion
from django.db import migrations, models


def seed_monasteries(apps, schema_editor):
    Monastery = apps.get_model('Discover', 'Monastery')
    Monastery.objects.bulk_create([
        Monastery(
            name='Holy Cross Monastery',
            slug='holy-cross-nteje',
            order_name='Congregation of the Holy Cross',
            location='Nteje, Anambra State',
            region='Anambra East',
            summary='A prayerful monastic community rooted in mission, silence, and service.',
            description='Holy Cross Monastery is a peaceful sanctuary where contemplative life and community service meet. The brothers are known for disciplined prayer, pastoral outreach, and serene hospitality for pilgrims and visitors.',
            directions='From Nteje, follow the road toward the parish church and continue until you see the monastic enclosure at the hilltop approach.',
            image_url='https://images.unsplash.com/photo-1507692049790-de58290a4334',
            is_published=True,
        ),
        Monastery(
            name='St. Benedict Monastery',
            slug='st-benedict-ozubulu',
            order_name='Order of Saint Benedict',
            location='Ozubulu, Anambra State',
            region='Ekwusigo',
            summary='A Benedictine haven of prayer, work, and balanced monastic living.',
            description='St. Benedict Monastery offers a rhythm of chapel prayer, manual work, and quiet reflection. It is valued for its strong Benedictine rule, disciplined hospitality, and carefully nurtured communal life.',
            directions='At Ozubulu, follow the road toward the central church junction and turn toward the monastic grounds beside the old farm entrance.',
            image_url='https://images.unsplash.com/photo-1470770841072-f978cf4d019e',
            is_published=True,
        ),
        Monastery(
            name='Carmelite Monastery',
            slug='carmelite-holy-family',
            order_name='Carmelite Order',
            location='Awka or nearby Anambra rural edge',
            region='Awka South',
            summary='A Carmelite refuge of silent prayer, reflection, and devotion to Mary.',
            description='The Carmelite Monastery is known for its deep love of prayer, the rosary, and contemplative life. Visitors find a serene atmosphere ideal for reflection, spiritual guidance, and quiet renewal.',
            directions='Proceed toward the Carmelite lane in the Awka area and follow the signs to the monastery chapel and guest house.',
            image_url='https://images.unsplash.com/photo-1494526585095-c41746248156',
            is_published=True,
        ),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('directions', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_monasteries, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PrayerIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('intention_type', models.CharField(choices=[('health', 'Health & healing'), ('thanksgiving', 'Thanksgiving'), ('family', 'Family harmony'), ('vocation', 'Vocation'), ('peace', 'Peace & country'), ('general', 'General intention')], default='general', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monastery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Discover.monastery')),
            ],
        ),
        migrations.CreateModel(
            name='RetreatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('stay_type', models.CharField(choices=[('silent', 'Silent retreat'), ('guided', 'Guided retreat'), ('family', 'Family stay'), ('group', 'Group retreat')], default='silent', max_length=50)),
                ('arrival_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(default=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monastery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Discover.monastery')),
            ],
        ),
    ]
